name: nextcloud container pre-publish

on:
  workflow_call:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Defaults to the reference or SHA for that event.
        required: false
        type: string
      dockerfile-dir:
        description: Dockerfile directory
        required: false
        type: string
    outputs:
      container-image-name:
        value: ${{ jobs.nextcloud-pre-publish.outputs.container-image-name }}
      nextcloud-version:
        value: ${{ jobs.nextcloud-pre-publish.outputs.nextcloud-version }}

jobs:
  nextcloud-pre-publish:
    runs-on: ubuntu-latest
    outputs:
      container-image-name: ${{ steps.container-image-name.outputs.VALUE }}
      nextcloud-version: ${{ steps.nextcloud-version.outputs.VERSION }}
    steps:
      - name: Compose container image name
        id: container-image-name
        run: echo "VALUE=${REPO_NAME#container-}" >>$GITHUB_OUTPUT
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Find out embedded nextcloud version
        id: nextcloud-version
        run: echo "VERSION=$(scripts/nextcloud-version.sh "${{ inputs.dockerfile-dir }}")" >>$GITHUB_OUTPUT
