name: Validate & publish (branch)

on:
  push:
    branches: [ main ]

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@e2802bbf8293c1f7a0801550713b78cab286677c

  get-version:
    needs: validate
    uses: anthochamp/dev-toolbox/.github/workflows/util-get-latest-git-version-tag.yml@e2802bbf8293c1f7a0801550713b78cab286677c

  pre-publish:
    needs: validate
    uses: ./.github/workflows/nextcloud-pre-publish.yml
    with:
      dockerfile-dir: src

  publish:
    needs: [validate, get-version, pre-publish]
    permissions:
      packages: write
      id-token: write # used for sigstore/fulcio identity challenge
    uses: anthochamp/dev-toolbox/.github/workflows/container-publish.yml@e2802bbf8293c1f7a0801550713b78cab286677c
    with:
      dockerfile-dir: src
      dhub-readme-file: ./CONTAINER.md
      version: ${{ needs.get-version.outputs.version }}
      alt-version: ${{ needs.pre-publish.outputs.nextcloud-version }}
      alt-version-prefix: nextcloud
      container-image-name: ${{ needs.pre-publish.outputs.container-image-name }}
      # libsmbclient fails to compile on linux/arm/v7
      build-platforms: linux/amd64,linux/arm64
    secrets:
      dhub-username: ${{ secrets.DHUB_USERNAME }}
      dhub-password: ${{ secrets.DHUB_PASSWORD }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-password: ${{ secrets.GITHUB_TOKEN }}
